### ISSUE TITLE
App Phase Provisioning Failed - Hadoop Env doesn't work

### ISSUE THREAD

**Issue by jensenity** [vinicelms/emr-monitoring-prometheus-grafana#7]
```
[
    {
      "Classification": "hadoop-env",
      "Configurations": [
        {
          "Classification": "export",
          "Properties": {
            "HADOOP_DATANODE_OPTS": "\"-javaagent:/etc/prometheus/jmx_prometheus_javaagent-0.14.0.jar=7001:/etc/hadoop/conf/hdfs_jmx_config_datanode.yaml -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=50103\"",
            "HADOOP_NAMENODE_OPTS": "\"-javaagent:/etc/prometheus/jmx_prometheus_javaagent-0.14.0.jar=7001:/etc/hadoop/conf/hdfs_jmx_config_namenode.yaml -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=50103\""
          }
        }
      ],
      "Properties": {}
    }
]
```

I tried adding your configuration to our AWS EMR 6.2 configuration and it kept falling in the app phase stage. In our puppet log, it just said that something was change and AWS EMR just terminated right away.

**Comment by vinicelms** [comment]
Hello, @jensenity.

Sorry about the delay to reply.

Previously I had a similar problem, but it didn't involve anything related to this project. If the size of the EMR cluster instances is too small, it will result in an error without much information. As this process you mentioned is just for changing the file settings, it wouldn't have anything related to the bootstrap process.

Try to create a cluster with more resources, with at least m5.xlarge instances and obviously with few services operating in the cluster. If you want more services, minimally use m5.2xlarge instances.

This issue even turned into a support ticket on AWS, which asked for a test with a slightly larger cluster.

**Comment by vinicelms** [comment]
No additional information.
