### ISSUE TITLE
【Help】How do I get dashboard template

### ISSUE THREAD

**Issue by RengarLee** [vinicelms/emr-monitoring-prometheus-grafana#8]
Nice Work！

Do I want the Grafana dashboard template used in the documentation and how can I get it?
I searched many places but couldn't find this template. If you can help, that would be greatly appreciated.

**Comment by mcl085** [comment]
@RengarLee did you find the dashboard template?

**Comment by vinicelms** [comment]
Hello, guys!

Sorry for the delay in responding to this issue.

As this dashboard may undergo changes or improvements by AWS, I will put the procedures in the documentation, so that everyone understands the process of obtaining the dashboards.

**Comment by vinicelms** [comment]
All files are already in the repository and the information is already in the documentation.

[Grafana Dashboard docs](https://github.com/vinicelms/emr-monitoring-prometheus-grafana?tab=readme-ov-file#grafana-dashboards)

**Comment by vinicelms** [comment]
All files are already in the repository and the information is already in the documentation.

[Grafana Dashboard docs](https://github.com/vinicelms/emr-monitoring-prometheus-grafana?tab=readme-ov-file#grafana-dashboards)
